# Generated by Django 5.2 on 2025-05-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_devicemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='devices',
            field=models.ManyToManyField(blank=True, to='service.devicemodel'),
        ),
    ]
