# Generated by Django 5.2 on 2025-05-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_servicerequest_devices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='taken',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='timeslot',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
