# Generated by Django 5.2 on 2025-06-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_alter_servicerequest_date_wastecollection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='New User', max_length=100),
        ),
    ]
