# Generated by Django 5.2 on 2025-06-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='emergency_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='urgent_request',
            field=models.BooleanField(default=False),
        ),
    ]
