# Generated by Django 5.2 on 2025-06-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_servicerequest_emergency_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dp',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='technician',
            name='dp',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='technician_pics/'),
        ),
    ]
