# Generated by Django 5.2 on 2025-06-17 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='location',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.address'),
        ),
    ]
