# Generated by Django 5.2 on 2025-06-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_remove_servicerequest_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastecollection',
            name='location',
        ),
    ]
